yarnPath: .yarn/releases/yarn-3.3.1.cjs

nodeLinker: pnp

pnpMode: loose

enableScripts: false

packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  styled-components@*:
    dependencies:
      react-is: '*'
  vite@*:
    dependencies:
      supports-color: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
    - 'win32'

  cpu:
    - 'x86'
    - 'x64'
    - 'arm64'
    - 'ia32'

  libc:
    - 'glibc'
    - 'musl'
